name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/lbuilder/LBuilder
            git pull
            composer install
            npm install && npm run dev
            php artisan migrate
            bash ./vendor/laravel/sail/bin/sail down
            bash ./vendor/laravel/sail/bin/sail up -d
            ./vendor/laravel/sail/bin/sail artisan migrate