name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/LBuilder
            git pull
            bash ./vendor/laravel/sail/bin/sail composer install
            bash ./vendor/laravel/sail/bin/sail npm install
            bash ./vendor/laravel/sail/bin/sail npm run build
            bash ./vendor/laravel/sail/bin/sail artisan migrate
            bash ./vendor/laravel/sail/bin/sail artisan migrate:refresh --path=/database/migrations/2023_08_17_184335_create_permission_tables.php
            bash ./vendor/laravel/sail/bin/sail artisan migrate:refresh --path=/database/migrations/2014_10_12_000000_create_users_table.php
            bash ./vendor/laravel/sail/bin/sail artisan db:seed --class=RolesAndPermissions
            bash ./vendor/laravel/sail/bin/sail artisan db:seed --class=AdminSeeder
            bash ./vendor/laravel/sail/bin/sail down
            bash ./vendor/laravel/sail/bin/sail up -d
